// <auto-generated />
using System;
using Directory_Service.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Directory_Service.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105150336_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Directory_Service.Domain.Department.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DepartmentId")
                        .HasName("pk_department");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("ParentId");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("Directory_Service.Domain.Department.DepartmentLocation", b =>
                {
                    b.Property<Guid>("DepartmentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_location_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("department_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("location_id")
                        .HasColumnType("uuid");

                    b.HasKey("DepartmentLocationId")
                        .HasName("pk_department_location");

                    b.HasIndex("department_id");

                    b.HasIndex("location_id");

                    b.ToTable("department_location", (string)null);
                });

            modelBuilder.Entity("Directory_Service.Domain.Department.DepartmentPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("department_position_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("department_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("position_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_department_position");

                    b.HasIndex("department_id");

                    b.HasIndex("position_id");

                    b.ToTable("department_position", (string)null);
                });

            modelBuilder.Entity("Directory_Service.Domain.Location.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_location_name");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("Directory_Service.Domain.Position.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_position");

                    b.ToTable("position", (string)null);
                });

            modelBuilder.Entity("Directory_Service.Domain.Department.Department", b =>
                {
                    b.HasOne("Directory_Service.Domain.Department.Department", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentDepartmentId");

                    b.HasOne("Directory_Service.Domain.Department.Department", null)
                        .WithMany("ChildrenDepartments")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Directory_Service.Domain.Department.DepartmentLocation", b =>
                {
                    b.HasOne("Directory_Service.Domain.Department.Department", "Department")
                        .WithMany("DepartmentLocations")
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Directory_Service.Domain.Location.Location", "Location")
                        .WithMany("DepartmentsLocations")
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Directory_Service.Domain.Department.DepartmentPosition", b =>
                {
                    b.HasOne("Directory_Service.Domain.Department.Department", "Department")
                        .WithMany("DepartmentPositions")
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Directory_Service.Domain.Position.Position", "Position")
                        .WithMany("DepartmentPosition")
                        .HasForeignKey("position_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Directory_Service.Domain.Location.Location", b =>
                {
                    b.OwnsOne("Directory_Service.Domain.Location.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("LocationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Building")
                                .HasColumnType("integer")
                                .HasColumnName("building");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("city");

                            b1.Property<int>("Flat")
                                .HasColumnType("integer")
                                .HasColumnName("flat");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("street");

                            b1.HasKey("LocationId");

                            b1.HasIndex("Building")
                                .IsUnique()
                                .HasDatabaseName("ix_location_building");

                            b1.HasIndex("City")
                                .IsUnique()
                                .HasDatabaseName("ix_location_city");

                            b1.HasIndex("Flat")
                                .IsUnique()
                                .HasDatabaseName("ix_location_flat");

                            b1.HasIndex("Street")
                                .IsUnique()
                                .HasDatabaseName("ix_location_street");

                            b1.ToTable("location");

                            b1.ToJson("Address");

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Directory_Service.Domain.Department.Department", b =>
                {
                    b.Navigation("ChildrenDepartments");

                    b.Navigation("DepartmentLocations");

                    b.Navigation("DepartmentPositions");
                });

            modelBuilder.Entity("Directory_Service.Domain.Location.Location", b =>
                {
                    b.Navigation("DepartmentsLocations");
                });

            modelBuilder.Entity("Directory_Service.Domain.Position.Position", b =>
                {
                    b.Navigation("DepartmentPosition");
                });
#pragma warning restore 612, 618
        }
    }
}
